llm:
  provider: OPENAI

  meta:
    model: gpt-5.6-luna
    reasoning:
      effort: medium

  http_client:
    verify: true
    timeout: 180
    api_url: https://api.openai.com/v1

vcs:
  provider: GITHUB

  http_client:
    verify: true
    timeout: 120
    api_url: https://api.github.com

  pagination:
    per_page: 100
    max_pages: 5

core:
  concurrency: 3

agent:
  enabled: false

prompt:
  inline_prompt_files:
    - ./.github/ai-review/python-qa-review.md

  context_prompt_files:
    - ./.github/ai-review/python-qa-review.md

  summary_prompt_files:
    - ./.github/ai-review/python-qa-review.md

  include_inline_system_prompts: true
  include_context_system_prompts: true
  include_summary_system_prompts: true

review:
  mode: FULL_FILE_DIFF
  dry_run: false
  ignore_pure_renames: true

  ignore_changes:
    - poetry.lock
    - .idea/*
    - allure-results/*
    - allure-report/*
    - allure-history/*

  max_inline_comments: 3
  max_context_comments: 8
  inline_comment_fallback: false

artifacts:
  llm_enabled: false
  vcs_enabled: false
