[project]
name = "ui-tests"
version = "0.1.0"
description = "Playwright UI tests"
authors = [
    { name = "Barbaron86", email = "kirill.molodykh@mail.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "pytest-playwright (>=0.9.0,<0.10.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.16.3,<0.17.0)"
]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
    "E", # Ошибки PEP8
    "W", # Предупреждения PEP8
    "F", # Критические ошибки и баги (undefined names)
    "I", # Автосортировка импортов (isort)
    "UP", # Обновление синтаксиса под Python 3.12
]
ignore = [
    "E501", # Игнорировать длину строки (для длинных селекторов Playwright)
    "PT004", # Разрешить фикстуры без return
    "W292", # Игнорировать отсутствие новой строки в конце файла
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

markers = [
    "ui: Маркировка для UI тестов ",
    "slow: Маркировка для медленных тестов",
    "smoke: Маркировка для smoke тестов",
    "critical: Маркировка для critical тестов",
    "regression: Маркировка для regression тестов",
    "registration: Маркировка для тестов, связанных с регистрацией пользователя",
    "authorization: Маркировка для тестов, связанных с авторизацией пользователя",
    "courses: Маркировка для тестов, связанных с курсами",
]
